name: ai-book-generator
type: gradio-space
sdk: streamlit

metadata:
  space_id: Chris4K/ai-book-generator
  original_url: https://huggingface.co/spaces/Chris4K/ai-book-generator

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"

# Updated: 2026-01-03 12:59:58
