# Educational values
AGE_RANGE = [3, 4, 5]
SKILL_DEVELOPMENT = [
    "Curiosity",
    "Imagination",
    "Communication",
    "Observation",
    "Adaptability",
    "Persistence",
    "Collaboration",
    "Emotional Intelligence",
    "Self-awareness",
    "Memory",
]
LEARNING_OBJECTIVES = [
    "Science exploration",
    "Nature observation",
    "History and social studies",
    "Language development",
    "Math concepts",
    "Fine motor skills" "Gross motor skills",
]

# emotionl values
THEME = [
    "Empathy",
    "Kindness",
    "Friendship",
    "Courage",
    "Diversity",
    "Imagination",
    "Perseverance",
    "Self-confidence",
    "Responsibility" "Gratitude",
]
MODD_OF_STORY = [
    "Lighthearted",
    "Funny",
    "Adventure",
    "Comforting",
    "Calm",
    "Educational",
    "Inspiring",
]
POSITIVE_MESSAGNG = [
    "Kindness and compassion",
    "Friendship and cooperation",
    "Respect for others and diversity",
    "Self-confidence and self-esteem",
    "Perseverance and resilience",
    "Honesty and integrity",
    "Responsibility and accountability",
    "Empathy and understanding",
    "Mindfulness and emotional regulation",
    "Creativity and imagination",
]

# Personal
GENDER = ["Male", "Female"]
GENRE = [
    "Fairy tales",
    "Biography",
    "Animal stories",
    "Adventure stories",
    "Rhyming books",
    "Concept books",
    "Folktales",
    "Nursery rhymes",
    "Science fiction",
    "Humorous books",
]
TOPIC = [
    "Animals (fiction and non-fiction)",
    "Friendship and relationships",
    "Family and home life",
    "Bedtime stories",
    "Colors and shapes",
    "Numbers and counting",
    "Alphabet and phonics",
    "Fairy tales and nursery rhymes",
    "Adventure and exploration",
    "Imagination and creativity",
]

TYPE_OF_MAIN_CHARACTER = [
    "Human",
    "Monkey",
    "Cat",
    "Caterpillar",
    "Dog",
    "Teddy bear",
    "Elephant",
    "Lions",
    "Penguins",
    "Monkeys",
    "Ducks",
    "Frogs",
    "Giraffes",
    "Tigers",
    "Whales",
    "Zebras",
    "Superhero",
    "Dinosaur",
    "Robot",
    "Aliens",
    "Dragons",
    "Pirates",
    "Princess",
    "Fairy",
    "Dragons",
    "Cyclops",
    "Yeti",
    "Bigfoot",
    "Goblins",
    "Trolls",
    "Ghosts",
    "Fire trucks",
    "Trains",
    "Race cars",
    "Construction vehicle",
    "Airplanes",
    "Helicopters",
    "Boats",
    "Spaceships",
    "Motorcycles",
    "Buses",
]
ANTAGONIST_TYPE = [
    "Witch",
    "Wizard",
    "Evil queen",
    "Evil king",
    "Monster",
    "Pirate",
    "Giant",
    "Robot",
    "Evil machine",
    "Human",
    "Monkey",
    "Cat",
    "Caterpillar",
    "Dog",
    "Teddy bear",
    "Elephant",
    "Lions",
    "Penguins",
    "Monkeys",
    "Ducks",
    "Frogs",
    "Giraffes",
    "Tigers",
    "Whales",
    "Zebras",
    "Superhero",
    "Dinosaur",
    "Robot",
    "Aliens",
    "Dragons",
    "Pirates",
    "Princess",
    "Fairy",
    "Dragons",
    "Cyclops",
    "Yeti",
    "Bigfoot",
    "Goblins",
    "Trolls",
    "Ghosts",
    "Fire trucks",
    "Trains",
    "Race cars",
    "Construction vehicle",
    "Airplanes",
    "Helicopters",
    "Boats",
    "Spaceships",
    "Motorcycles",
    "Buses",
]
SUPPORTING_CHARACTER_TYPE = ANTAGONIST_TYPE
SETTINGS = [
    "Forests",
    "Underwater",
    "Imaginary world",
    "Cityscapes",
    "Countryside",
    "Outer space",
    "Castle",
    "School",
    "Magical kingdom",
    "Enchanted forest",
    "Circus",
    "City",
]
RESOLUTION = [
    "Apologizing and making amends",
    "Learning to share and take turns",
    "Standing up for oneself and others",
    "Overcoming fear and facing challenges",
    "Solving a problem or mystery",
    "Learning a lesson or moral value",
    "Forgiving and moving on",
    "Accepting differences and celebrating diversity",
    "Helping others and showing kindness",
    "Making a new friend or finding common ground",
    "Discovering a new passion or talent",
    "Resolving a conflict peacefully and fairly",
    "Making a sacrifice for the greater good",
    "Learning from mistakes and taking responsibility",
    "Understanding the consequences of one's actions",
    "Finding a creative or innovative solution",
    "Embracing change and adapting to new situations",
    "Discovering the importance of teamwork and cooperation",
    "Making a tough decision and sticking to it",
    "Embracing the power of imagination and creativity",
]
